// ----- Users endponits ----- //

### Sign Up
POST http://localhost:3306/users/signup
Content-Type: application/json

{
    "fullName": "João Martins",
    "email": "joao@gmail.com",
    "password": "123456",
    "role": "normal"
}

### Login
POST http://localhost:3306/users/login
Content-Type: application/json

{
    "email": "gioivieira@gmail.com",
    "password": "123456"
}

// ----- Bands endponits ----- //

### Create Band
POST http://localhost:3306/bands/create_band
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTE3MDM1MCwiZXhwIjoxNjgxMjU2NzUwfQ.lBxjTVjrl77pyiKH809ZcsyZon44cxV9Jay1tmEh3nc

{
    "name": "Adele",
    "musicGenre": "Pop",
    "responsible": "Adele"
}

### Get Band
GET http://localhost:3306/bands/band
Content-Type: application/json

{
    "bandId": "a31f621d-faa7-44a0-9a74-7de2673018f7"
}

// ----- Shows endponits ----- //

### Get All Shows
GET http://localhost:3306/shows
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTE3MDM1MCwiZXhwIjoxNjgxMjU2NzUwfQ.lBxjTVjrl77pyiKH809ZcsyZon44cxV9Jay1tmEh3nc

### Get Festival Day Schedule
GET http://localhost:3306/shows/schedule?week_day=sunday
Content-Type: application/json

### Create Show
POST http://localhost:3306/shows/create_show
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTE3MDM1MCwiZXhwIjoxNjgxMjU2NzUwfQ.lBxjTVjrl77pyiKH809ZcsyZon44cxV9Jay1tmEh3nc

{
    "weekDay": "sunday",
    "startTime": "14:00:00", 
    "endTime": "15:00:00",
    "bandId": "4cd82228-ca62-461c-9959-3c733b68f2e0"
}

// ----- Events endponits ----- //

### Get All Events
GET http://localhost:3306/events
Content-Type: application/application/json

### Create Event
POST http://localhost:3306/events/create_event
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTE3MDM1MCwiZXhwIjoxNjgxMjU2NzUwfQ.lBxjTVjrl77pyiKH809ZcsyZon44cxV9Jay1tmEh3nc

{
    "eventName": "Caju Festival"
}

// ----- Tickets endponits ----- //

### Get All Events Tickets
GET http://localhost:3306/tickets
Content-Type: application/application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTE3MDM1MCwiZXhwIjoxNjgxMjU2NzUwfQ.lBxjTVjrl77pyiKH809ZcsyZon44cxV9Jay1tmEh3nc

### Create Event Tickets
POST http://localhost:3306/tickets/create_event_tickets
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTE3MDM1MCwiZXhwIjoxNjgxMjU2NzUwfQ.lBxjTVjrl77pyiKH809ZcsyZon44cxV9Jay1tmEh3nc

{
    "ticketQuantity": 200,
    "eventId": "07220826-c12e-417f-b481-e72b0b59e077"
}

### Buy Ticket
POST http://localhost:3306/tickets/create_event_tickets_trade
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTE3MDM1MCwiZXhwIjoxNjgxMjU2NzUwfQ.lBxjTVjrl77pyiKH809ZcsyZon44cxV9Jay1tmEh3nc

{
    "amountOfTicketsToBuy": 150,
    "eventName": "Caju Festival"
}