// ----- Users endponits ----- //

### Sign Up
POST http://localhost:3306/users/signup
Content-Type: application/json

{
    "fullName": "João Martins",
    "email": "joao@gmail.com",
    "password": "123456",
    "role": "admin"
}

### Login
POST http://localhost:3306/users/login
Content-Type: application/json

{
    "email": "joao@gmail.com",
    "password": "123456"
}

// ----- Bands endponits ----- //

### Create Band
POST http://localhost:3306/bands/create_band
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTMzMzUwMSwiZXhwIjoxNjgxNDE5OTAxfQ.3bHM9u2zam_fCfx_UsImkPSM3wEiag7azJDLA-u5e5E

{
    "name": "The Kooks",
    "musicGenre": "Indie",
    "responsible": "Luke"
}

### Get Band
GET http://localhost:3306/bands/band
Content-Type: application/json

{
    "bandId": "36c46fc5-318e-40fb-8d74-78006ae263d6"
}

// ----- Shows endponits ----- //

### Get All Shows
GET http://localhost:3306/shows
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTMzMzUwMSwiZXhwIjoxNjgxNDE5OTAxfQ.3bHM9u2zam_fCfx_UsImkPSM3wEiag7azJDLA-u5e5E

### Get Festival Day Schedule
GET http://localhost:3306/shows/schedule?week_day=sunday
Content-Type: application/json

### Create Show
POST http://localhost:3306/shows/create_show
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTMzMzUwMSwiZXhwIjoxNjgxNDE5OTAxfQ.3bHM9u2zam_fCfx_UsImkPSM3wEiag7azJDLA-u5e5E

{
    "weekDay": "sunday",
    "startTime": "14:00:00", 
    "endTime": "15:00:00",
    "bandId": "36c46fc5-318e-40fb-8d74-78006ae263d6"
}

// ----- Events endponits ----- //

### Get All Events
GET http://localhost:3306/events
Content-Type: application/application/json

### Create Event
POST http://localhost:3306/events/create_event
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTMzMzUwMSwiZXhwIjoxNjgxNDE5OTAxfQ.3bHM9u2zam_fCfx_UsImkPSM3wEiag7azJDLA-u5e5E

{
    "eventName": "Indie Festival"
}

// ----- Tickets endponits ----- //

### Get All Events Tickets
GET http://localhost:3306/tickets
Content-Type: application/application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTMzMzUwMSwiZXhwIjoxNjgxNDE5OTAxfQ.3bHM9u2zam_fCfx_UsImkPSM3wEiag7azJDLA-u5e5E

### Create Event Tickets
POST http://localhost:3306/tickets/create_event_tickets
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTMzMzUwMSwiZXhwIjoxNjgxNDE5OTAxfQ.3bHM9u2zam_fCfx_UsImkPSM3wEiag7azJDLA-u5e5E

{
    "ticketQuantity": 200,
    "eventId": "b631d4f4-4860-44b2-aa3b-23ec8dba98d8"
}

### Buy Ticket
POST http://localhost:3306/tickets/create_event_tickets_trade
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YTBhOTkwLWUyMWYtNGM0ZC05OGNjLTI5NzI1NjMyODA2NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MTMzMzUwMSwiZXhwIjoxNjgxNDE5OTAxfQ.3bHM9u2zam_fCfx_UsImkPSM3wEiag7azJDLA-u5e5E

{
    "amountOfTicketsToBuy": 20,
    "eventName": "Indie Festival"
}